"""Adding username, password and role to ComaniesModel

Revision ID: 064df9fcadaf
Revises: 8d7f4dccfdac
Create Date: 2021-12-09 11:20:00.025467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '064df9fcadaf'
down_revision = '8d7f4dccfdac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('aberto', 'em_atendimento', 'fechado', name='enumstatus'), nullable=True),
    sa.Column('type', sa.Enum('computador', 'notebook', 'impressora', 'nobreak', name='enumtype'), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('release_date', sa.DateTime(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.Column('solution', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('technician_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('companies', sa.Column('username', sa.String(length=150), nullable=True))
    op.add_column('companies', sa.Column('password', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('role', sa.String(length=150), nullable=True))
    op.drop_constraint('companies_key_id_key', 'companies', type_='unique')
    op.drop_constraint('companies_key_id_fkey', 'companies', type_='foreignkey')
    op.drop_column('companies', 'key_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('key_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('companies_key_id_fkey', 'companies', 'keys', ['key_id'], ['id'])
    op.create_unique_constraint('companies_key_id_key', 'companies', ['key_id'])
    op.drop_column('companies', 'role')
    op.drop_column('companies', 'password')
    op.drop_column('companies', 'username')
    op.drop_table('orders')
    # ### end Alembic commands ###
