"""empty message

Revision ID: 1699ba2ea6df
Revises: 7be52390f167
Create Date: 2021-12-15 08:50:27.884630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1699ba2ea6df'
down_revision = '7be52390f167'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('owners', sa.Column('active', sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, 'owners', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'owners', type_='unique')
    op.drop_column('owners', 'active')
    # ### end Alembic commands ###
