"""empty message

Revision ID: 2004dda8f73c
Revises: 2a6b384b8a81
Create Date: 2021-12-16 20:44:34.537366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2004dda8f73c'
down_revision = '2a6b384b8a81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'companies', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companies', type_='unique')
    # ### end Alembic commands ###
