"""empty message

Revision ID: 245c117c5f47
Revises: 3af9d3bc7244
Create Date: 2021-12-10 21:00:02.474158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '245c117c5f47'
down_revision = '3af9d3bc7244'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'technician_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'technician_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
