"""empty message

Revision ID: 2a6b384b8a81
Revises: 3261d926f2ac
Create Date: 2021-12-16 13:08:42.800446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a6b384b8a81'
down_revision = '3261d926f2ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('technicians', sa.Column('role', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('technicians', 'role')
    # ### end Alembic commands ###
