"""adicionando password_hash a tabela technicians

Revision ID: 2fb048eeae99
Revises: ed07f4eaca56
Create Date: 2021-12-08 10:38:41.823914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fb048eeae99'
down_revision = 'ed07f4eaca56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('technicians', sa.Column('password_hash', sa.String(), nullable=False))
    op.drop_column('technicians', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('technicians', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('technicians', 'password_hash')
    # ### end Alembic commands ###
