"""empty message

Revision ID: 3af9d3bc7244
Revises: a0ac5ac78a1d
Create Date: 2021-12-10 13:45:08.376858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3af9d3bc7244'
down_revision = 'a0ac5ac78a1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'technician_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'technician_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
