"""empty message

Revision ID: 44283c41213d
Revises: 3af9d3bc7244
Create Date: 2021-12-13 10:51:13.517497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44283c41213d'
down_revision = '3af9d3bc7244'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('active', sa.Boolean(), nullable=False))
    op.drop_constraint('users_registration_key', 'users', type_='unique')
    op.drop_column('users', 'registration')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('registration', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_unique_constraint('users_registration_key', 'users', ['registration'])
    op.drop_column('users', 'active')
    # ### end Alembic commands ###
