"""adding active to company_model

Revision ID: 78ce714c1725
Revises: d079029f1c87
Create Date: 2021-12-13 14:20:20.865384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78ce714c1725'
down_revision = 'd079029f1c87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'active')
    # ### end Alembic commands ###
