"""empty message

Revision ID: 7be52390f167
Revises: fc9cbc2b0079
Create Date: 2021-12-14 20:44:28.648523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7be52390f167'
down_revision = 'fc9cbc2b0079'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.drop_table('keys')
    op.add_column('companies', sa.Column('password_hash', sa.String(), nullable=False))
    op.add_column('companies', sa.Column('active', sa.Boolean(), nullable=False))
    op.alter_column('companies', 'username',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.drop_column('companies', 'password')
    op.drop_constraint('technicians_registration_key', 'technicians', type_='unique')
    op.drop_column('technicians', 'registration')
    op.add_column('users', sa.Column('position', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('active', sa.Boolean(), nullable=False))
    op.drop_column('users', 'registration')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('registration', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('users', 'active')
    op.drop_column('users', 'position')
    op.add_column('technicians', sa.Column('registration', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_unique_constraint('technicians_registration_key', 'technicians', ['registration'])
    op.add_column('companies', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('companies', 'username',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.drop_column('companies', 'active')
    op.drop_column('companies', 'password_hash')
    op.create_table('keys',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='keys_pkey')
    )
    op.drop_table('owners')
    # ### end Alembic commands ###
