"""empty message

Revision ID: 830bfe785e00
Revises: 1699ba2ea6df
Create Date: 2021-12-15 11:32:10.777245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '830bfe785e00'
down_revision = '1699ba2ea6df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('owners', sa.Column('active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('owners', 'active')
    # ### end Alembic commands ###
