"""alter columnmn username and password_hash

Revision ID: 9b31730becee
Revises: cec1eb632f77
Create Date: 2021-12-13 15:03:02.923668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b31730becee'
down_revision = 'cec1eb632f77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'username',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('companies', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('companies', 'username',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    # ### end Alembic commands ###
