"""empty message

Revision ID: cb16fc2136a3
Revises: 7dc0ac050a72
Create Date: 2021-12-13 12:16:02.938612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb16fc2136a3'
down_revision = '7dc0ac050a72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('technicians_registration_key', 'technicians', type_='unique')
    op.drop_column('technicians', 'registration')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('technicians', sa.Column('registration', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_unique_constraint('technicians_registration_key', 'technicians', ['registration'])
    # ### end Alembic commands ###
