"""create atribute position and class EnumRole

Revision ID: cec1eb632f77
Revises: 78ce714c1725
Create Date: 2021-12-13 14:44:36.482520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cec1eb632f77'
down_revision = '78ce714c1725'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('position', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'position')
    # ### end Alembic commands ###
