"""company password to password_hash

Revision ID: d079029f1c87
Revises: 44283c41213d
Create Date: 2021-12-13 14:02:49.777367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd079029f1c87'
down_revision = '44283c41213d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('password_hash', sa.String(), nullable=True))
    op.drop_column('companies', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('companies', 'password_hash')
    # ### end Alembic commands ###
