"""alter column for unique True

Revision ID: fb97558b7a10
Revises: 5fa87517968f
Create Date: 2021-12-14 16:07:25.001968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb97558b7a10'
down_revision = '5fa87517968f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'owners', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'owners', type_='unique')
    # ### end Alembic commands ###
